export const JAIPUR_LOCALITIES = [
  'Malviya Nagar',
  'C-Scheme',
  'Vaishali Nagar',
  'Mansarovar',
  'Tonk Road',
  'Raja Park',
  'Gopalpura',
  'Bani Park',
  'Jhotwara',
  'Sodala',
  'Pratap Nagar',
  'Jagatpura',
  'Vidyadhar Nagar',
  'Civil Lines',
  'Shastri Nagar',
  'Adarsh Nagar',
  'Jawahar Nagar',
  'Lal Kothi',
  'Muralipura',
  'Sanganer',
  'Sitapura',
  'Bapu Nagar'
];
