name: TheAcharProject
options:
  bundleIdPrefix: com.example

targets:
  TheAcharProject:
    type: application
    platform: iOS
    sources: ["."]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.theacharproject
      SWIFT_VERSION: 5.9
      IPHONEOS_DEPLOYMENT_TARGET: 16.0
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGNING_ALLOWED: NO