import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';

export async function POST(req: Request) {
  try {
    const { boxName } = await req.json();

    if (!boxName || !boxName.trim()) {
      return NextResponse.json({ success: false, error: 'boxName is required' }, { status: 400 });
    }

    // Find all ACTIVE subscriptions
    const activeSubscriptions = await prisma.subscription.findMany({
      where: { status: 'ACTIVE' }
    });

    let createdCount = 0;

    // Use transaction to ensure consistency
    await prisma.$transaction(
      activeSubscriptions.map(sub => {
        return prisma.subscriptionDispatch.upsert({
          where: {
            // Since we want to make sure a sub can only have one dispatch per boxName,
            // we can look up by a unique index or just do a manual conditional insert.
            // Since we didn't add a unique compound index (subscriptionId, boxName) in schema,
            // we can query and insert. Let's do it in a transaction safely.
            id: 'non-existent-placeholder' // Forces create if not matched, but let's write a safe custom check
          },
          update: {},
          create: {
            subscriptionId: sub.id,
            boxName: boxName.trim(),
            status: 'PENDING',
            paymentMethod: 'COD',
            notes: 'Batch-generated by admin'
          }
        });
      })
    );

    // Wait! Let's write a safe non-duplicating loop inside a database transaction
    const results = await prisma.$transaction(async (tx) => {
      let created = 0;
      for (const sub of activeSubscriptions) {
        const existing = await tx.subscriptionDispatch.findFirst({
          where: {
            subscriptionId: sub.id,
            boxName: boxName.trim()
          }
        });
        if (!existing) {
          await tx.subscriptionDispatch.create({
            data: {
              subscriptionId: sub.id,
              boxName: boxName.trim(),
              status: 'PENDING',
              paymentMethod: 'COD',
              notes: 'Batch-generated by admin'
            }
          });
          created++;
        }
      }
      return created;
    });

    createdCount = results;

    return NextResponse.json({ success: true, createdCount });
  } catch (error) {
    console.error('Error generating subscription dispatches:', error);
    const msg = error instanceof Error ? error.message : 'Failed to generate dispatches';
    return NextResponse.json({ success: false, error: msg }, { status: 500 });
  }
}
